name: Build CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Install dependencies 
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install -y git-core gnupg flex bison build-essential zip curl zlib1g-dev libc6-dev-i386 x11proto-core-dev libx11-dev lib32z1-dev libgl1-mesa-dev libxml2-utils xsltproc unzip fontconfig libssl-dev

    - name: Download prebuilts toolchain
      run: |
        bash build_kernel.sh gcc
        bash build_kernel.sh clang

    - name: Configure
      run: bash build_kernel.sh prepare

    - name: Build kernel
      run: |
        bash build_kernel.sh build
